esphome:
  name: sunrisealarm
  friendly_name: SunriseAlarm

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  logs:
    component: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sunrisealarm Fallback Hotspot"
    password: ""

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "Button1"
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "Button2"
  - platform: gpio
    pin:
      number: GPIO18
      mode: INPUT_PULLUP
      inverted: True
    name: "RotaryButton"

  - platform: homeassistant
    name: "Alarm 1 State"
    entity_id: input_boolean.alarm1_state
    id: alarm1_state
  - platform: homeassistant
    name: "Alarm Paused State"
    entity_id: input_boolean.alarm_paused
    id: alarm_paused
  - platform: homeassistant
    name: "Alarm 2 State"
    entity_id: input_boolean.alarm2_state
    id: alarm2_state
  - platform: homeassistant
    name: "Monday1"
    entity_id: input_boolean.alarm1_monday
    id: alarm1_monday
  - platform: homeassistant
    name: "Tuesday1"
    entity_id: input_boolean.alarm1_tuesday
    id: alarm1_tuesday
  - platform: homeassistant
    name: "Wednesday1"
    entity_id: input_boolean.alarm1_wednesday
    id: alarm1_wednesday
  - platform: homeassistant
    name: "Thursday1"
    entity_id: input_boolean.alarm1_thursday
    id: alarm1_thursday
  - platform: homeassistant
    name: "Friday1"
    entity_id: input_boolean.alarm1_friday
    id: alarm1_friday
  - platform: homeassistant
    name: "Saturday1"
    entity_id: input_boolean.alarm1_saturday
    id: alarm1_saturday
  - platform: homeassistant
    name: "Sunday1"
    entity_id: input_boolean.alarm1_sunday
    id: alarm1_sunday
  - platform: homeassistant
    name: "Monday2"
    entity_id: input_boolean.alarm2_monday
    id: alarm2_monday
  - platform: homeassistant
    name: "Tuesday2"
    entity_id: input_boolean.alarm2_tuesday
    id: alarm2_tuesday
  - platform: homeassistant
    name: "Wednesday2"
    entity_id: input_boolean.alarm2_wednesday
    id: alarm2_wednesday
  - platform: homeassistant
    name: "Thursday2"
    entity_id: input_boolean.alarm2_thursday
    id: alarm2_thursday
  - platform: homeassistant
    name: "Friday2"
    entity_id: input_boolean.alarm2_friday
    id: alarm2_friday
  - platform: homeassistant
    name: "Saturday2"
    entity_id: input_boolean.alarm2_saturday
    id: alarm2_saturday
  - platform: homeassistant
    name: "Sunday2"
    entity_id: input_boolean.alarm2_sunday
    id: alarm2_sunday

sensor:
  - platform: rotary_encoder
    name: "Rotary Encoder"
    pin_a:
      number: GPIO19
      inverted: true
      mode:
        input: true
        pullup: true
    pin_b: 
      number: GPIO21
      inverted: true
      mode:
        input: true
        pullup: true
    on_clockwise:
      - logger.log: "Turned Clockwise"
      - display.page.show_next: oled
    on_anticlockwise:
      - logger.log: "Turned Anticlockwise"
      - display.page.show_previous: oled

i2s_audio:
  - id: i2s_out
    i2s_lrclk_pin: GPIO23
    i2s_bclk_pin: GPIO22

media_player:
  - platform: i2s_audio
    id: media_out
    name: Speaker
    dac_type: external
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO4
    mode: mono

time:
  - platform: homeassistant
    id: esptime

text_sensor:
  - platform: homeassistant
    entity_id: input_datetime.alarm1_time
    name: "Alarm 1 Time"
    id: alarm1_time
  - platform: homeassistant
    entity_id: input_datetime.alarm2_time
    name: "Alarm 2 Time"
    id: alarm2_time

font:
  - file: "ComicSansMS3.ttf"
    id: font1
    size: 48
  - file: "ComicSansMS3.ttf"
    id: font2
    size: 16
  - file: "ComicSansMS3.ttf"
    id: font3
    size: 20

spi:
  clk_pin: GPIO33
  mosi_pin: GPIO32

display:
  - platform: ssd1351_spi
    model: "SSD1351 128x128"
    id: oled
    cs_pin: GPIO26
    dc_pin: GPIO25
    reset_pin: GPIO27
    brightness: 0.1
    pages:
      - id: page1
        lambda: |-
          auto time = id(esptime).now();
          it.printf(0, 0, id(font1), "%02d:%02d", time.hour, time.minute);

          // Helper function to get minutes since midnight
          auto get_minutes = [](const std::string& time_str) -> int {
            int hour = std::stoi(time_str.substr(0, 2));
            int minute = std::stoi(time_str.substr(3, 2));
            return hour * 60 + minute;
          };

          // Get current day and minutes
          int current_day = time.day_of_week - 2; // 0 = Monday
          int current_minutes = time.hour * 60 + time.minute;
          
          // Check both alarms
          bool found_next = false;
          int min_wait = 7 * 24 * 60; // Maximum wait time (one week in minutes)
          std::string next_time = "";
          std::string next_day = "";
          
          // Helper lambda to check alarm
          auto check_alarm = [&](bool alarm_state, const std::string& alarm_time,
                                bool mon, bool tue, bool wed, bool thu,
                                bool fri, bool sat, bool sun) {
            if (!alarm_state) return;
            
            int alarm_minutes = get_minutes(alarm_time);
            bool days[7] = {mon, tue, wed, thu, fri, sat, sun};
            const char* day_names[7] = {"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"};
            
            // Check each enabled day
            for (int d = 0; d < 7; d++) {
              if (!days[d]) continue;
              
              int day_diff = (d - current_day + 7) % 7;
              int wait_minutes = day_diff * 24 * 60 + (alarm_minutes - current_minutes);
              
              // If same day and alarm already passed, add a week
              if (day_diff == 0 && alarm_minutes <= current_minutes) {
                wait_minutes += 7 * 24 * 60;
              }
              
              if (wait_minutes < min_wait) {
                min_wait = wait_minutes;
                next_time = alarm_time.substr(0,5);
                // If it's today and hasn't passed, don't show day
                if (day_diff == 0 && alarm_minutes > current_minutes) {
                  next_day = "Today";
                } else if (day_diff == 1) {
                  next_day = "Tomorrow";
                } else {
                  next_day = day_names[d];
                }
                found_next = true;
              }
            }
          };
          
          // Check both alarms
          check_alarm(
            id(alarm1_state).state,
            id(alarm1_time).state,
            id(alarm1_monday).state,
            id(alarm1_tuesday).state,
            id(alarm1_wednesday).state,
            id(alarm1_thursday).state,
            id(alarm1_friday).state,
            id(alarm1_saturday).state,
            id(alarm1_sunday).state
          );
          
          check_alarm(
            id(alarm2_state).state,
            id(alarm2_time).state,
            id(alarm2_monday).state,
            id(alarm2_tuesday).state,
            id(alarm2_wednesday).state,
            id(alarm2_thursday).state,
            id(alarm2_friday).state,
            id(alarm2_saturday).state,
            id(alarm2_sunday).state
          );
          
          // Display next alarm if found
          if (found_next) {
            it.printf(0, 80, id(font2), "%s %s", next_day.c_str(), next_time.c_str());
          }
      - id: page2
        lambda: |-

          std::string days1 = "";
          if (id(alarm1_monday).state) days1 += "m ";
          if (id(alarm1_tuesday).state) days1 += "tu ";
          if (id(alarm1_wednesday).state) days1 += "w ";
          if (id(alarm1_thursday).state) days1 += "th ";
          if (id(alarm1_friday).state) days1 += "f ";
          if (id(alarm1_saturday).state) days1 += "sa ";
          if (id(alarm1_sunday).state) days1 += "su";
        
          it.printf(0, 20, id(font3), "Alarm 1: %s", id(alarm1_state).state ? "ON" : "OFF");
          std::string alarm1_time_hhmm = id(alarm1_time).state.substr(0, 5);
          it.printf(0, 50, id(font3), "%s", alarm1_time_hhmm.c_str());
          it.printf(0, 80, id(font3), "%s", days1.c_str());
      - id: page3
        lambda: |-

          std::string days2 = "";
          if (id(alarm2_monday).state) days2 += "m ";
          if (id(alarm2_tuesday).state) days2 += "tu ";
          if (id(alarm2_wednesday).state) days2 += "w ";
          if (id(alarm2_thursday).state) days2 += "th ";
          if (id(alarm2_friday).state) days2 += "f ";
          if (id(alarm2_saturday).state) days2 += "sa ";
          if (id(alarm2_sunday).state) days2 += "su";

          it.printf(0, 20, id(font3), "Alarm 2: %s", id(alarm2_state).state ? "ON" : "OFF");
          std::string alarm2_time_hhmm = id(alarm2_time).state.substr(0, 5);
          it.printf(0, 50, id(font3), "%s", alarm2_time_hhmm.c_str());
          it.printf(0, 80, id(font3), "%s", days2.c_str());